services:
  
  gateway:
    image: nginx:alpine
    container_name: breezy-api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile.dev    # Use Dockerfile.dev for development, Dockerfile for production
    container_name: breezy-auth-service
    environment:
      - DB_CONNECTION=mongodb://auth-mongo:27017/auth
    volumes:
      - ./backend/auth:/app         # Mount local source code into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:latest
    container_name: breezy-auth-mongo
    volumes:
      - auth-mongo-data:/data/db

  user-service:
    build:
      context: ./backend/user
      dockerfile: Dockerfile.dev
    container_name: breezy-user-service
    environment:
      - DB_CONNECTION=mongodb://user-mongo:27017/user
    volumes:
      - ./backend/user:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:latest
    container_name: breezy-user-mongo
    volumes:
      - user-mongo-data:/data/db
    networks:
      - app-network


volumes:
  auth-mongo-data:
  user-mongo-data:

networks:
  app-network:
    driver: bridge
