x-env: &global-env
  FRONTEND_ORIGIN: http://localhost:3000    # Frontend URL
  GATEWAY_ORIGIN:  http://localhost:8080    # API Gateway URL

services:
  
  # -- NGINX GATEWAY --
  gateway:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-gateway
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - documentation-service
      - gateway-service
      - auth-service
      - user-service
      - post-service
  
  # -- DOCUMENTATION SERVICE --
  documentation-service:
    build:
      context: ./backend/docs
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-documentation-service
    environment: *global-env
    volumes:
      - ./backend/docs:/app         # Mount local source code into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
  
  # -- GATEWAY SERVICE --
  gateway-service:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-gateway-service
    environment: *global-env
    volumes:
      - ./backend/gateway:/app         # Mount local source code into container (remove for production)
      - /app/node_modules               # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network

  # -- AUTH SERVICE --
  auth-service:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-auth-service
    environment:
      <<: *global-env
      MONGO_URI: mongodb://auth-mongo:27017/auth
    volumes:
      - ./backend/auth:/app         # Mount local source code into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:latest
    restart: always
    container_name: breezy-auth-mongo
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - app-network

  # -- USER SERVICE --
  user-service:
    build:
      context: ./backend/user
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-user-service
    environment:
      <<: *global-env
      MONGO_URI: mongodb://user-mongo:27017/user
    volumes:
      - ./backend/user:/app         # Mount local source code into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:latest
    restart: always
    container_name: breezy-user-mongo
    volumes:
      - user-mongo-data:/data/db
    networks:
      - app-network

  # -- POST SERVICE --
  post-service:
    build:
      context: ./backend/post
      dockerfile: Dockerfile.dev
    restart: always
    container_name: breezy-post-service
    environment:
      <<: *global-env
      MONGO_URI: mongodb://post-mongo:27017/post
    volumes:
      - ./backend/post:/app         # Mount local source code into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
    depends_on:
      - post-mongo

  post-mongo:
    image: mongo:latest
    restart: always
    container_name: breezy-post-mongo
    volumes:
      - post-mongo-data:/data/db
    networks:
      - app-network

volumes:
  auth-mongo-data:
  user-mongo-data:
  post-mongo-data:

networks:
  app-network:
    driver: bridge