services:
  
  gateway:
    image: nginx:alpine
    container_name: breezy-api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - auth-service
  
  documentation-service:
    build:
      context: ./backend/docs
      dockerfile: Dockerfile
    restart: always
    container_name: breezy-documentation-service
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile.dev    # Use Dockerfile.dev for development, Dockerfile for production
    container_name: breezy-auth-service
    environment:
      - MONGO_URI=mongodb://auth-mongo:27017/auth
    volumes:
      - ./backend/auth:/app         # Mount local source czode into container (remove for production)
      - /app/node_modules           # Prevent overwriting node_modules from host (remove for production)
    networks:
      - app-network
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:latest
    container_name: breezy-auth-mongo
    volumes:
      - auth-mongo-data:/data/db

volumes:
  auth-mongo-data:

networks:
  app-network:
    driver: bridge