version: '3.8'

services:
  
  api-gateway:
    image: nginx:alpine
    container_name: breezy-api-gateway
    ports:
      - "80:80"
    volumes:
      - ./backend/gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - auth-service

  # auth-service:
  #   build: ./backend/auth
  #   container_name: breezy-auth-service
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - DB_CONNECTION=...
  #   depends_on:
  #     - mongo-1

#   mongo-1:
#     image: mongo:latest
#     container_name: breezy-mongo1
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
